export default [
  {
    product_id: "P001",
    name: "Organic Honey",
    description:
      "Raw, unfiltered organic honey, perfect for tea, baking, or as a spread.",
    price: 350,
    brand: "Pure Nature",
    stock_quantity: 150,
    rating: 4.7,
    category_id: "C001",
    image_url: "/images/products/organic_honey.jpg",
    attributes: {
      size: "500g",
      origin: "India",
      type: "Raw",
    },
  },
  {
    product_id: "P002",
    name: "Whole Wheat Bread",
    description: "Healthy whole wheat bread made with 100% whole grain flour.",
    price: 50,
    brand: "Baker's Delight",
    stock_quantity: 200,
    rating: 4.3,
    category_id: "C001",
    image_url: "/images/products/whole_wheat_bread.jpg",
    attributes: {
      weight: "400g",
      type: "Whole Wheat",
      freshness: "3 days",
    },
  },
  {
    product_id: "P003",
    name: "Oatmeal (Steel-Cut)",
    description:
      "Nutritious steel-cut oatmeal, rich in fiber and ideal for breakfast.",
    price: 120,
    brand: "Oats Delight",
    stock_quantity: 180,
    rating: 4.6,
    category_id: "C001",
    image_url: "/images/products/oatmeal_steel_cut.jpg",
    attributes: {
      size: "500g",
      flavor: "Plain",
      gluten_free: "Yes",
    },
  },
  {
    product_id: "P004",
    name: "Canned Tomato Sauce",
    description:
      "Rich and flavorful canned tomato sauce, perfect for pasta or pizza.",
    price: 80,
    brand: "Fresh Taste",
    stock_quantity: 250,
    rating: 4.2,
    category_id: "C001",
    image_url: "/images/products/canned_tomato_sauce.jpg",
    attributes: {
      size: "400g",
      organic: "Yes",
      spice_level: "Mild",
    },
  },
  {
    product_id: "P005",
    name: "Almond Milk (Unsweetened)",
    description:
      "Dairy-free almond milk with no added sugar, perfect for lactose intolerant individuals.",
    price: 150,
    brand: "AlmondJoy",
    stock_quantity: 130,
    rating: 4.4,
    category_id: "C001",
    image_url: "/images/products/almond_milk_unsweetened.jpg",
    attributes: {
      size: "1L",
      organic: "Yes",
      ingredients: "Almonds, Water",
    },
  },
  {
    product_id: "P006",
    name: "Organic Baby Carrots",
    description:
      "Fresh, organic baby carrots, perfect for snacks or adding to salads.",
    price: 60,
    brand: "Fresh Farms",
    stock_quantity: 300,
    rating: 4.5,
    category_id: "C001",
    image_url: "/images/products/organic_baby_carrots.jpg",
    attributes: {
      weight: "250g",
      organic: "Yes",
      freshness: "2 weeks",
    },
  },
  {
    product_id: "P007",
    name: "Canned Black Beans",
    description:
      "Canned black beans, rich in protein and perfect for tacos, salads, or soups.",
    price: 45,
    brand: "Bean Co.",
    stock_quantity: 400,
    rating: 4.1,
    category_id: "C001",
    image_url: "/images/products/canned_black_beans.jpg",
    attributes: {
      size: "400g",
      organic: "No",
      cooking_time: "15 minutes",
    },
  },
  {
    product_id: "P008",
    name: "Peanut Butter (Creamy)",
    description:
      "Creamy peanut butter made from roasted peanuts, great for spreading or snacking.",
    price: 150,
    brand: "Nutty Spread",
    stock_quantity: 180,
    rating: 4.8,
    category_id: "C001",
    image_url: "/images/products/peanut_butter_creamy.jpg",
    attributes: {
      size: "500g",
      type: "Creamy",
      gluten_free: "Yes",
    },
  },
  {
    product_id: "P009",
    name: "Frozen Mixed Vegetables",
    description:
      "A blend of carrots, peas, corn, and green beans, perfect for stir-fries or soups.",
    price: 120,
    brand: "Quick Veggies",
    stock_quantity: 220,
    rating: 4.3,
    category_id: "C001",
    image_url: "/images/products/frozen_mixed_vegetables.jpg",
    attributes: {
      weight: "500g",
      organic: "Yes",
      freezing_method: "Flash Frozen",
    },
  },
  {
    product_id: "P010",
    name: "Coconut Oil (Virgin, Cold-Pressed)",
    description:
      "100% virgin coconut oil, perfect for cooking or as a natural moisturizer.",
    price: 300,
    brand: "Coco Pure",
    stock_quantity: 160,
    rating: 4.6,
    category_id: "C001",
    image_url: "/images/products/coconut_oil_virgin.jpg",
    attributes: {
      size: "500ml",
      organic: "Yes",
      smell: "Mild Coconut",
    },
    // Mobile
  },
  {
    product_id: "P011",
    name: "iPhone 15 Pro Max",
    description:
      "The latest iPhone with an advanced A17 Bionic chip, stunning 48MP camera, and 5G capabilities.",
    price: 139999,
    brand: "Apple",
    stock_quantity: 120,
    rating: 4.8,
    category_id: "C002",
    image_url: "/images/products/iphone_15_pro_max.jpg",
    attributes: {
      color: "Space Black",
      storage: "256GB",
      battery_life: "20 hours",
      connectivity: "5G, Wi-Fi 6",
    },
  },
  {
    product_id: "P012",
    name: "Samsung Galaxy S23 Ultra",
    description:
      "A flagship device featuring a 200MP camera, Snapdragon 8 Gen 2 processor, and a massive 6.8-inch display.",
    price: 124999,
    brand: "Samsung",
    stock_quantity: 150,
    rating: 4.7,
    category_id: "C002",
    image_url: "/images/products/samsung_galaxy_s23_ultra.jpg",
    attributes: {
      color: "Phantom Black",
      storage: "512GB",
      battery_life: "22 hours",
      connectivity: "5G, Wi-Fi 6",
    },
  },
  {
    product_id: "P013",
    name: "Google Pixel 8 Pro",
    description:
      "Google's flagship phone with AI-powered camera features, Tensor G3 chip, and a stunning 6.7-inch OLED display.",
    price: 99999,
    brand: "Google",
    stock_quantity: 100,
    rating: 4.6,
    category_id: "C002",
    image_url: "/images/products/google_pixel_8_pro.jpg",
    attributes: {
      color: "Obsidian",
      storage: "128GB",
      battery_life: "18 hours",
      connectivity: "5G, Wi-Fi 6E",
    },
  },
  {
    product_id: "P014",
    name: "OnePlus 11",
    description:
      "A performance-oriented phone featuring Snapdragon 8 Gen 2, 50MP triple camera, and a 120Hz AMOLED display.",
    price: 54999,
    brand: "OnePlus",
    stock_quantity: 200,
    rating: 4.5,
    category_id: "C002",
    image_url: "/images/products/oneplus_11.jpg",
    attributes: {
      color: "Titan Black",
      storage: "256GB",
      battery_life: "24 hours",
      connectivity: "5G, Wi-Fi 6",
    },
  },
  {
    product_id: "P015",
    name: "Xiaomi 13 Pro",
    description:
      "Xiaomi's premium flagship featuring Leica cameras, Snapdragon 8 Gen 2, and a 120Hz AMOLED display.",
    price: 74999,
    brand: "Xiaomi",
    stock_quantity: 180,
    rating: 4.4,
    category_id: "C002",
    image_url: "/images/products/xiaomi_13_pro.jpg",
    attributes: {
      color: "Ceramic White",
      storage: "256GB",
      battery_life: "18 hours",
      connectivity: "5G, Wi-Fi 6",
    },
  },
  {
    product_id: "P016",
    name: "Sony Xperia 1 V",
    description:
      "Sony's flagship phone with a 6.5-inch 4K OLED display, Snapdragon 8 Gen 2, and a 50MP triple camera setup.",
    price: 99990,
    brand: "Sony",
    stock_quantity: 80,
    rating: 4.6,
    category_id: "C002",
    image_url: "/images/products/sony_xperia_1v.jpg",
    attributes: {
      color: "Frosted Black",
      storage: "256GB",
      battery_life: "22 hours",
      connectivity: "5G, Wi-Fi 6",
    },
  },
  {
    product_id: "P017",
    name: "Samsung Galaxy Z Fold 5",
    description:
      "A revolutionary foldable phone with a 7.6-inch Dynamic AMOLED display, Snapdragon 8 Gen 2, and 12GB RAM.",
    price: 179999,
    brand: "Samsung",
    stock_quantity: 60,
    rating: 4.9,
    category_id: "C002",
    image_url: "/images/products/samsung_galaxy_z_fold_5.jpg",
    attributes: {
      color: "Phantom Black",
      storage: "512GB",
      battery_life: "18 hours",
      connectivity: "5G, Wi-Fi 6",
    },
  },
  {
    product_id: "P018",
    name: "Motorola Edge 40 Pro",
    description:
      "A flagship device featuring a 50MP camera, Snapdragon 8 Gen 2, and a curved 6.7-inch OLED display.",
    price: 64999,
    brand: "Motorola",
    stock_quantity: 150,
    rating: 4.3,
    category_id: "C002",
    image_url: "/images/products/motorola_edge_40_pro.jpg",
    attributes: {
      color: "Interstellar Black",
      storage: "256GB",
      battery_life: "20 hours",
      connectivity: "5G, Wi-Fi 6",
    },
  },
  {
    product_id: "P019",
    name: "Oppo Find X6 Pro",
    description:
      "Oppo's flagship phone with a 50MP triple camera setup, Snapdragon 8 Gen 2, and a 6.82-inch OLED display.",
    price: 74999,
    brand: "Oppo",
    stock_quantity: 110,
    rating: 4.5,
    category_id: "C002",
    image_url: "/images/products/oppo_find_x6_pro.jpg",
    attributes: {
      color: "Green",
      storage: "256GB",
      battery_life: "24 hours",
      connectivity: "5G, Wi-Fi 6",
    },
  },
  {
    product_id: "P020",
    name: "Realme GT 2 Pro",
    description:
      "Realme's flagship phone with a 50MP camera, Snapdragon 8 Gen 1, and a 6.7-inch AMOLED display.",
    price: 55999,
    brand: "Realme",
    stock_quantity: 190,
    rating: 4.4,
    category_id: "C002",
    image_url: "/images/products/realme_gt_2_pro.jpg",
    attributes: {
      color: "Paper White",
      storage: "256GB",
      battery_life: "18 hours",
      connectivity: "5G, Wi-Fi 6",
    },
  },
  {
    // Fashion
    product_id: "P021",
    name: "Men's Slim Fit Jeans",
    description:
      "Classic slim-fit jeans for men made with soft denim, perfect for casual or semi-formal wear.",
    price: 1999,
    brand: "Levi's",
    stock_quantity: 250,
    rating: 4.5,
    category_id: "C003",
    subcategory_name:"Men's",
    image_url: "/images/products/mens_slim_fit_jeans.jpg",
    attributes: {
      color: "Indigo",
      size: "32-34",
      material: "Cotton, Spandex",
      fit_type: "Slim",
    },
  },
  {
    product_id: "P022",
    name: "Women's Floral Dress",
    description:
      "Elegant floral print dress, ideal for casual outings, made with breathable cotton fabric.",
    price: 2499,
    subcategory_name:"Women",
    brand: "Zara",
    stock_quantity: 180,
    rating: 4.7,
    category_id: "C003",
    image_url: "/images/products/womens_floral_dress.jpg",
    attributes: {
      color: "Blue & White",
      size: "S, M, L",
      material: "Cotton",
      occasion: "Casual",
    },
  },
  {
    product_id: "P023",
    name: "Men's Leather Jacket",
    description:
      "Stylish and durable leather jacket with a slim cut, perfect for both casual and formal wear.",
    price: 5999,
    brand: "AllSaints",
    stock_quantity: 120,
    rating: 4.6,
    category_id: "C003",
    subcategory_name:"Men's",
    image_url: "/images/products/mens_leather_jacket.jpg",
    attributes: {
      color: "Black",
      size: "M, L, XL",
      material: "Genuine Leather",
      style: "Biker",
    },
  },
  {
    product_id: "P024",
    name: "Women's High-Waisted Skirt",
    description:
      "Chic high-waisted skirt, designed with a flattering A-line shape, perfect for work or weekend outings.",
    price: 1299,
    brand: "H&M",
    stock_quantity: 300,
    rating: 4.3,
    category_id: "C003",
    image_url: "/images/products/womens_high_waisted_skirt.jpg",
    attributes: {
      color: "Black",
      size: "S, M, L",
      material: "Polyester",
      style: "A-Line",
    },
  },
  {
    product_id: "P025",
    name: "Men's Polo Shirt",
    description:
      "Classic men's polo shirt, made with soft cotton fabric, perfect for casual or semi-formal events.",
    price: 999,
    brand: "Tommy Hilfiger",
    stock_quantity: 250,
    rating: 4.5,
    category_id: "C003",
    subcategory_name:"Men's",
    image_url: "/images/products/mens_polo_shirt.jpg",
    attributes: {
      color: "Navy Blue",
      size: "M, L, XL",
      material: "Cotton",
      fit_type: "Regular",
    },
  },
  {
    product_id: "P026",
    name: "Women's Sneakers",
    description:
      "Comfortable and trendy women's sneakers with a stylish design, perfect for everyday wear.",
    price: 3999,
    brand: "Nike",
    stock_quantity: 150,
    rating: 4.8,
    category_id: "C003",
    subcategory_name:"Women's",
    image_url: "/images/products/womens_sneakers.jpg",
    attributes: {
      color: "White & Pink",
      size: "6-9",
      material: "Synthetic, Rubber",
      style: "Casual",
    },
  },
  {
    product_id: "P027",
    name: "Men's Casual Chinos",
    description:
      "Stylish and comfortable chinos for men, made from lightweight cotton, perfect for a smart-casual look.",
    price: 2199,
    brand: "Uniqlo",
    stock_quantity: 200,
    rating: 4.4,
    category_id: "C003",
    subcategory_name:"Men's",
    image_url: "/images/products/mens_casual_chinos.jpg",
    attributes: {
      color: "Beige",
      size: "32-36",
      material: "Cotton",
      fit_type: "Regular",
    },
  },
  {
    product_id: "P028",
    name: "Women's Winter Coat",
    description:
      "Cozy and warm winter coat with faux fur lining, perfect for cold weather, and comes with a stylish belt.",
    price: 5999,
    brand: "Mango",
    stock_quantity: 130,
    rating: 4.8,
    category_id: "C003",
    subcategory_name:"Women's",
    image_url: "/images/products/womens_winter_coat.jpg",
    attributes: {
      color: "Dark Grey",
      size: "S, M, L",
      material: "Wool Blend",
      style: "Double-Breasted",
    },
  },
  {
    product_id: "P029",
    name: "Men's Running Shoes",
    description:
      "High-performance running shoes designed with advanced cushioning technology for maximum comfort.",
    price: 4499,
    brand: "Adidas",
    stock_quantity: 180,
    rating: 4.7,
    category_id: "C003",
    subcategory_name:"Men's",
    image_url: "/images/products/mens_running_shoes.jpg",
    attributes: {
      color: "Black & Red",
      size: "7-12",
      material: "Mesh, Rubber",
      style: "Sport",
    },
  },
  {
    product_id: "P030",
    name: "Girls Printed Hooded Neck Yellow Sweater",
    description:
      "Styles  Girls Printed Hooded Neck Black Sweater looking beautiful.",
    price: 1299,
    brand: "PUMA",
    stock_quantity: 250,
    rating: 4.2,
    category_id: "C003",
    subcategory_name:"Kid's",
    image_url: "/images/products/6-12-months-babycardigan-button-2color-yellow-s-momisy-original-imagkyt8h9xtphhh.webp",
    attributes: {
      color: "Black",
      lens_type: "Polarized",
      material: "Acetate",
      style: "Oversized",
    },
    // electronics
  },

  {
    product_id: "P031",
    name: "Samsung 55-inch 4K Smart TV",
    description:
      "Experience vivid colors and crystal-clear resolution with this 55-inch 4K UHD Smart TV from Samsung.",
    price: 49999,
    brand: "Samsung",
    stock_quantity: 80,
    rating: 4.7,
    category_id: "C004",
    subcategory_name:"TV",
    image_url: "/images/products/samsung_55_inch_tv.jpg",
    attributes: {
      screen_size: "55 inches",
      resolution: "4K UHD",
      smart_features: "Yes",
      connectivity: "Wi-Fi, Bluetooth",
    },
  },
  {
    product_id: "P032",
    name: "Apple MacBook Pro 14-inch M2 Chip",
    description:
      "Powerful 14-inch MacBook Pro with Apple's M2 chip, ideal for professionals who need high performance.",
    price: 169999,
    brand: "Apple",
    stock_quantity: 50,
    rating: 4.8,
    category_id: "C004",
    subcategory_name:"Laptop",
    image_url: "/images/products/macbook_pro_14_m2.jpg",
    attributes: {
      screen_size: "14 inches",
      processor: "Apple M2",
      ram: "16GB",
      storage: "512GB SSD",
    },
  },
  {
    product_id: "P033",
    name: "Sony PlayStation 5 Console",
    description:
      "Next-generation gaming with ultra-fast load times, incredible graphics, and immersive gameplay on the PS5.",
    price: 49999,
    brand: "Sony",
    stock_quantity: 120,
    rating: 4.9,
    category_id: "C004",
    image_url: "/images/products/ps5_console.jpg",
    attributes: {
      storage: "825GB SSD",
      connectivity: "Wi-Fi, Bluetooth",
      color: "White",
      features: "Ultra HD Blu-ray",
    },
  },
  {
    product_id: "P034",
    name: "Bose QuietComfort 45 Noise-Canceling Headphones",
    description:
      "Over-ear headphones with world-class noise cancellation and incredible sound quality for a premium listening experience.",
    price: 29999,
    brand: "Bose",
    stock_quantity: 150,
    rating: 4.7,
    category_id: "C004",
    subcategory_name:"Headphone",
    image_url: "/images/products/bose_quietcomfort_45.jpg",
    attributes: {
      color: "Black",
      battery_life: "24 hours",
      connectivity: "Bluetooth, Wired",
      noise_cancellation: "Active",
    },
  },
  {
    product_id: "P035",
    name: "Apple AirPods Pro (2nd Generation)",
    description:
      "Active noise cancellation and superior sound quality with the new AirPods Pro for a truly immersive audio experience.",
    price: 24999,
    brand: "Apple",
    stock_quantity: 200,
    rating: 4.6,
    category_id: "C004",
    subcategory_name:"Airpods",
    image_url: "/images/products/airpods_pro_2.jpg",
    attributes: {
      color: "White",
      battery_life: "6 hours",
      connectivity: "Bluetooth",
      noise_cancellation: "Active",
    },
  },
  {
    product_id: "P036",
    name: "Canon EOS 90D DSLR Camera",
    description:
      "Capture stunning photos and 4K videos with the Canon EOS 90D, offering advanced autofocus and high-quality image processing.",
    price: 109999,
    brand: "Canon",
    stock_quantity: 80,
    rating: 4.8,
    category_id: "C004",
    subcategory_name:"Camera",
    image_url: "/images/products/canon_eos_90d.jpg",
    attributes: {
      resolution: "32.5 MP",
      video_resolution: "4K UHD",
      sensor_type: "APS-C",
      connectivity: "Wi-Fi, Bluetooth",
    },
  },
  {
    product_id: "P037",
    name: "Samsung Galaxy Tab S8 Ultra",
    description:
      "Large 14.6-inch AMOLED display tablet with high performance for both work and entertainment, powered by Snapdragon 8 Gen 1.",
    price: 85999,
    brand: "Samsung",
    stock_quantity: 60,
    rating: 4.7,
    category_id: "C004",
    subcategory_name:"Tablets",
    image_url: "/images/products/samsung_galaxy_tab_s8.jpg",
    attributes: {
      screen_size: "14.6 inches",
      processor: "Snapdragon 8 Gen 1",
      storage: "128GB",
      battery_life: "14 hours",
    },
  },
  {
    product_id: "P038",
    name: "DJI Air 2S Drone",
    description:
      "Compact and powerful drone with a 1-inch sensor and 5.4K video recording, perfect for professional photographers and hobbyists alike.",
    price: 74999,
    brand: "DJI",
    stock_quantity: 40,
    rating: 4.9,
    category_id: "C004",
    subcategory_name:"Drones",
    image_url: "/images/products/dji_air_2s_drone.jpg",
    attributes: {
      camera_resolution: "20 MP",
      max_flight_time: "31 minutes",
      video_resolution: "5.4K",
      connectivity: "Wi-Fi, Bluetooth",
    },
  },
  {
    product_id: "P039",
    name: "LG 27-inch 4K UltraGear Gaming Monitor",
    description:
      "4K UHD gaming monitor with NVIDIA G-SYNC, 1ms response time, and a 144Hz refresh rate for a smooth gaming experience.",
    price: 32999,
    brand: "LG",
    stock_quantity: 90,
    rating: 4.6,
    category_id: "C004",
    subcategory_name:"Laptop",
    image_url: "/images/products/lg_27_inch_4k_monitor.jpg",
    attributes: {
      screen_size: "27 inches",
      resolution: "4K UHD",
      refresh_rate: "144Hz",
      connectivity: "HDMI, DisplayPort",
    },
  },
  {
    product_id: "P040",
    name: "Amazon Echo Show 10 (3rd Gen)",
    description:
      "Smart display with Alexa and a 10.1-inch HD screen that swivels to follow you as you move, making it perfect for video calls and entertainment.",
    price: 24999,
    brand: "Amazon",
    stock_quantity: 150,
    rating: 4.7,
    category_id: "C004",
    image_url: "/images/products/echo_show_10.jpg",
    attributes: {
      screen_size: "10.1 inches",
      smart_assistant: "Alexa",
      connectivity: "Wi-Fi",
      features: "Video Calls, Smart Home Control",
    },
  },
  {
    product_id: "P041",
    name: "LG 8kg Front Load Washing Machine",
    description:
      "Efficient and eco-friendly washing machine with 6 Motion Direct Drive technology for a cleaner and quieter wash.",
    price: 32999,
    brand: "LG",
    stock_quantity: 120,
    rating: 4.6,
    category_id: "C006",
    image_url: "/images/products/lg_8kg_front_load_washing_machine.jpg",
    attributes: {
      capacity: "8 kg",
      wash_type: "Front Load",
      spin_speed: "1400 RPM",
      energy_rating: "5 Star",
    },
  },
  {
    product_id: "P042",
    name: "Samsung 253L Double Door Refrigerator",
    description:
      "Space-saving 253L refrigerator with a sleek design, energy-efficient cooling system, and advanced features.",
    price: 28999,
    brand: "Samsung",
    stock_quantity: 80,
    rating: 4.7,
    category_id: "C006",
    image_url: "/images/products/samsung_253L_refrigerator.jpg",
    attributes: {
      capacity: "253L",
      type: "Double Door",
      energy_rating: "4 Star",
      features: "Frost Free, Digital Inverter",
    },
  },
  {
    product_id: "P043",
    name: "Philips 1.7L Electric Kettle",
    description:
      "Fast-boiling electric kettle with automatic shut-off and boil-dry protection, perfect for quick tea or coffee.",
    price: 2499,
    brand: "Philips",
    stock_quantity: 200,
    rating: 4.5,
    category_id: "C006",
    image_url: "/images/products/philips_1.7L_electric_kettle.jpg",
    attributes: {
      capacity: "1.7L",
      material: "Stainless Steel",
      features: "Boil-Dry Protection, Auto Shut-off",
      power: "1500W",
    },
  },
  {
    product_id: "P044",
    name: "Bosch 13 Place Settings Dishwasher",
    description:
      "Efficient and silent dishwasher with 13 place settings, multiple wash programs, and energy-efficient features.",
    price: 49999,
    brand: "Bosch",
    stock_quantity: 70,
    rating: 4.8,
    category_id: "C006",
    image_url: "/images/products/bosch_13_place_settings_dishwasher.jpg",
    attributes: {
      capacity: "13 Place Settings",
      type: "Built-in",
      energy_rating: "A++",
      features: "Multiple Wash Programs, Eco Mode",
    },
  },
  {
    product_id: "P045",
    name: "Mi 1.5 Ton 5 Star Split AC",
    description:
      "Energy-efficient air conditioner with advanced cooling technology and fast cooling mode, perfect for summer heat.",
    price: 35999,
    brand: "Mi",
    stock_quantity: 100,
    rating: 4.7,
    category_id: "C006",
    image_url: "/images/products/mi_1.5ton_5star_split_ac.jpg",
    attributes: {
      capacity: "1.5 Ton",
      energy_rating: "5 Star",
      cooling_capacity: "5200W",
      features: "Fast Cooling, Sleep Mode",
    },
  },
  {
    product_id: "P046",
    name: "Panasonic 32L Convection Microwave Oven",
    description:
      "Microwave oven with convection and grill features, perfect for baking, grilling, and reheating meals with ease.",
    price: 10999,
    brand: "Panasonic",
    stock_quantity: 150,
    rating: 4.6,
    category_id: "C006",
    image_url: "/images/products/panasonic_32L_convection_microwave_oven.jpg",
    attributes: {
      capacity: "32L",
      type: "Convection",
      power: "900W",
      features: "Grill, Auto Cook, Defrost",
    },
  },
  {
    product_id: "P047",
    name: "Kenstar 25L Air Cooler",
    description:
      "Portable air cooler with 25L capacity, ideal for cooling medium-sized rooms during hot weather.",
    price: 4499,
    brand: "Kenstar",
    stock_quantity: 180,
    rating: 4.3,
    category_id: "C006",
    image_url: "/images/products/kenstar_25L_air_cooler.jpg",
    attributes: {
      capacity: "25L",
      type: "Tower",
      cooling_area: "Up to 150 sq. ft.",
      features: "Air Purification, Humidity Control",
    },
  },
  {
    product_id: "P048",
    name: "Whirlpool 7kg Top Load Washing Machine",
    description:
      "Smart washing machine with 6th Sense technology, efficient cleaning, and optimal water usage.",
    price: 24999,
    brand: "Whirlpool",
    stock_quantity: 130,
    rating: 4.5,
    category_id: "C006",
    image_url: "/images/products/whirlpool_7kg_top_load_washing_machine.jpg",
    attributes: {
      capacity: "7 kg",
      wash_type: "Top Load",
      spin_speed: "720 RPM",
      features: "6th Sense Technology, Hard Water Wash",
    },
  },
  {
    product_id: "P049",
    name: "Usha 1200W Steam Iron",
    description:
      "Steam iron with ceramic soleplate and powerful steam output, designed for smooth and wrinkle-free clothes.",
    price: 1799,
    brand: "Usha",
    stock_quantity: 220,
    rating: 4.4,
    category_id: "C006",
    image_url: "/images/products/usha_1200W_steam_iron.jpg",
    attributes: {
      power: "1200W",
      material: "Ceramic Soleplate",
      features: "Steam Burst, Vertical Steam",
      water_tank_capacity: "250ml",
    },
  },
  {
    product_id: "P050",
    name: "Crompton 1200W Mixer Grinder",
    description:
      "Durable and powerful mixer grinder with 3 jars, ideal for grinding spices, making smoothies, and more.",
    price: 2599,
    brand: "Crompton",
    stock_quantity: 200,
    rating: 4.5,
    category_id: "C006",
    image_url: "/images/products/crompton_1200W_mixer_grinder.jpg",
    attributes: {
      power: "1200W",
      jars: "3",
      material: "Stainless Steel",
      features: "Overload Protection, 3 Speed Control",
    },
  },
  {
    product_id: "P051",
    name: "Wooden Dining Chair",
    description: "Elegant wooden chair to complement your dining table.",
    price: 2499.99,
    brand: "FurniStyle",
    stock_quantity: 150,
    rating: 4.2,
    category_id: "C005",
    image_url: "/images/products/wooden-dining-chair.jpg",
    attributes: {
      material: "Teak Wood",
      color: "Natural Brown",
      weight: "5kg",
    },
  },
  {
    product_id: "P052",
    name: "Luxury Lipstick",
    description: "Premium lipstick with a rich, long-lasting color.",
    price: 899.99,
    brand: "BeautyGlow",
    stock_quantity: 500,
    rating: 4.7,
    category_id: "C008",
    image_url: "/images/products/luxury-lipstick.jpg",
    attributes: {
      color: "Red Velvet",
      finish: "Matte",
      weight: "3g",
    },
  },
  {
    product_id: "P053",
    name: "Electric Scooter",
    description:
      "Eco-friendly and efficient electric scooter for daily commute.",
    price: 45000,
    brand: "GreenRide",
    stock_quantity: 30,
    rating: 4.6,
    category_id: "C009",
    image_url: "/images/products/electric-scooter.jpg",
    attributes: {
      range: "50km per charge",
      battery_type: "Lithium-ion",
      speed: "25 km/h",
    },
  },
  {
    product_id: "P054",
    name: "Ergonomic Office Chair",
    description:
      "An ergonomic office chair designed for maximum comfort and support during long hours of work.",
    price: 7999.99,
    brand: "ComfortPlus",
    stock_quantity: 50,
    rating: 4.6,
    category_id: "C005", // Category for Home and Furniture
    image_url: "/images/products/ergonomic-office-chair.jpg",
    attributes: {
      color: "Black",
      material: "Mesh Back, Leather Seat",
      dimensions: "Height: 120cm, Width: 60cm, Depth: 60cm",
      weight: "15kg",
      features: [
        "Adjustable Height",
        "Lumbar Support",
        "360° Swivel",
        "Reclining Function",
        "Armrests",
      ],
    },
  },
  {
    product_id: "P055",
    name: "Long-Lasting Kajal",
    description:
      "A smooth, jet-black kajal pencil that delivers bold, smudge-proof, and long-lasting color for your eyes.",
    price: 299.99,
    brand: "GlamEyes",
    stock_quantity: 200,
    rating: 4.6,
    category_id: "C008", // Category for Beauty Toy & More
    image_url: "/images/products/long-lasting-kajal.jpg",
    attributes: {
      color: "Black",
      type: "Pencil",
      durability: "Up to 12 hours",
      water_resistant: "Yes",
      features: [
        "Smudge-Proof",
        "Rich Pigment",
        "Easy to Apply",
        "Dermatologically Tested",
      ],
    },
  },
  {
    product_id: "P056",
    name: "Sport Motorcycle",
    description:
      "A high-performance sport motorcycle designed for speed and agility on the road.",
    price: 79999.99,
    brand: "SpeedRider",
    stock_quantity: 50,
    rating: 4.9,
    category_id: "C009", // Category for Two Wheeler
    image_url: "/images/products/sport-motorcycle.jpg",
    attributes: {
      color: "Red",
      engine_capacity: "1000cc",
      top_speed: "250 km/h",
      weight: "190kg",
      features: [
        "ABS Braking",
        "LED Headlights",
        "Smart Dashboard",
        "Fuel Efficiency",
      ],
    },
  },
  {
    product_id: "P057",
    name: "Royal Enfield Bullet",
    description:
      "The iconic Royal Enfield Bullet, known for its classic design, powerful engine, and unmatched road presence.",
    price: 169999.99,
    brand: "Royal Enfield",
    stock_quantity: 25,
    rating: 4.8,
    category_id: "C009", // Category for Two Wheeler
    image_url: "/images/products/royal-enfield-bullet.jpg",
    attributes: {
      color: "Chrome Silver",
      engine_capacity: "350cc",
      top_speed: "130 km/h",
      weight: "192kg",
      features: [
        "Classic Design",
        "Single Cylinder",
        "ABS Braking",
        "Chrome Finish",
      ],
    },
  },
  {
    product_id: "P058",
    name: "Luxury Leather Sofa",
    description:
      "A premium leather sofa with plush cushions, perfect for adding comfort and style to any living room.",
    price: 24999.99,
    brand: "ComfortLiving",
    stock_quantity: 50,
    rating: 4.7,
    category_id: "C005", // Category for Home and Furniture
    image_url: "/images/products/luxury-leather-sofa.jpg",
    attributes: {
      color: "Brown",
      material: "Genuine Leather",
      dimensions: "85 x 40 x 35 inches",
      weight: "65kg",
      features: [
        "Durable",
        "Easy to Clean",
        "Premium Cushions",
        "Modern Design",
      ],
    },
  },
  {
    product_id: "P059",
    name: "Nail Polish - Classic Red",
    description:
      "A premium quality nail polish in a classic red shade, providing a smooth finish with long-lasting wear.",
    price: 299.99,
    brand: "BeautyShine",
    stock_quantity: 200,
    rating: 4.8,
    category_id: "C008", // Category for Beauty
    image_url: "/images/products/nail-polish-classic-red.jpg",
    attributes: {
      color: "Red",
      volume: "10 ml",
      finish: "Glossy",
      drying_time: "2 minutes",
      features: [
        "Chip Resistant",
        "Quick Drying",
        "Long-Lasting",
        "Vegan Formula",
      ],
    },
  },
  {
    product_id: "P060",
    name: "Queen Size Memory Foam Bed",
    description:
      "A comfortable queen-sized bed with memory foam mattress, offering excellent support and a restful night’s sleep.",
    price: 24999.99,
    brand: "Sleepwell",
    stock_quantity: 50,
    rating: 4.6,
    category_id: "C005", // Category for Home and Furniture
    image_url: "/images/products/queen-size-memory-foam-bed.jpg",
    attributes: {
      size: "Queen",
      material: "Wood & Memory Foam",
      color: "Dark Brown",
      features: [
        "Memory Foam Mattress",
        "Wooden Frame",
        "Durable & Sturdy",
        "Comfortable for All Sleep Positions",
      ],
    },
  },
];
